version: '3.7'

services:
    frontend:
        image: nginx
        volumes:
            - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./frontend/dist:/usr/share/nginx/html:ro
        ports:
            - 7123:80
        restart: unless-stopped

    api:
        build:
            context: ./api
        volumes:
            - ./config.ts:/usr/src/config.ts:ro
            - ./frontend/src/contract/types.ts:/usr/src/frontend/src/contract/types.ts:ro
        ports:
            - 5123:8081
        depends_on:
            - db
        restart: unless-stopped
    
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        env_file:
            - .env
        volumes:
            - ./db:/var/lib/postgresql/data
        restart: unless-stopped